### ISSUE TITLE
Java locustfile?

### ISSUE THREAD

**Issue by SkylerLutz** [AbdelrhmanHamouda/locust-k8s-operator#172]
Must the locustfile/tests be written in python? Is Java supported? I need to performance test a containerized app with a proprietary non-http protocol that only has a Java client api. Thanks

**Comment by treenerd** [comment]
@SkylerLutz wouldn't this be more a question in https://github.com/locustio/locust ?
This operator is made to rollout locust on k8s and may it is not the scope of a k8s operator to implement java inside the locust application.

**Comment by AbdelrhmanHamouda** [comment]
hello @SkylerLutz, thank you for taking the time to report this. As @treenerd had kindly pointed out, this question is better to be posted in the locust project since it is the tool that is doing the performance testing. 

From experience, i can tell you that indeed it is possible to write tests in java and there are projects that enable you to do so. That being said, it is more complex to go down this path because you will need to have a deeper understanding of locust as a tool and some of the "under the hood" processes. In addition, you will have harder time finding support when it comes to possible potential issues you may run into because of scale for example.
