### ISSUE TITLE
[Custom request] Promethues metric locust_running is always zero 

### ISSUE THREAD

**Issue by naga-awone** [AbdelrhmanHamouda/locust-k8s-operator#189]
Promethues metric locust_running is always zero  during distributed load tests, any clues?

**Comment by naga-awone** [comment]
sample data 
{__name__="locust_running", batch_kubernetes_io_controller_uid="1203b659-63c9-4c51-967f-5e3d07c851f8", batch_kubernetes_io_job_name="prj-100007-test-master",  controller_uid="1203b659-63c9-4c51-967f-5e3d07c851f8", instance="172.31.5.133:9646", job="kubernetes-pods", job_name="prj-100007-test-master", locust_io_role="master", managed_by="locust-k8s-operator", namespace="locust", node="ip-172-31-7-36.us-east-2.compute.internal", performance_test_name="prj-100007.test", performance_test_pod_name="prj-100007-test-master", pod="prj-100007-test-master-j6x9p"}

**Comment by naga-awone** [comment]
<img width="1459" alt="image" src="https://github.com/AbdelrhmanHamouda/locust-k8s-operator/assets/98945797/0005a72f-ed9b-456e-8923-1857c0bf331a">

**Comment by AbdelrhmanHamouda** [comment]
Hello @naga-awone, 
Thank you for taking the time to post this question and for your patience. I personally have stopped using this metric very early in the observability journey. I can't give you solid answer for why it's always 0. the metric is read directly from locust and that would be the root cause.  

However, as i mentioned, it is not worth investing in as it is not useful in a cloud context IMHO. The way the metric works and how cloud resources work are contradictory. the metric assumes long running "server" where you launch tests manually and for that you need an indicator for if "locust is running". However, in a cloud context, the resources are only around for the duration of the test and if there is no running test, then no running resources. 

The way I finally detected "locust is running" is by simply checking if the pods that are consistency & predictably labeled and annotated are running using default k8s metrics. 

moreover, you can simply use the presence of the metrics as an indicator for test running and absence as indicator for tests not running. 


Happy to help further if needed. I'll leave this issue open so you can follow up if needed.

**Comment by naga-awone** [comment]
@AbdelrhmanHamouda , Thanks for you time


I understand your perspective on its limitations in a cloud environment. 
I appreciate your suggestion to monitor the Kubernetes pods directly. Leveraging default Kubernetes metrics to track the status of the pods sounds like a more hack approach for determining if tests are running.
I am currently checking workers_running_count https://github.com/ContainerSolutions/locust_exporter/blob/f44dac5bc76834b8c830a3f12f170c16ef976773/main.go#L124
	locustWorkersRunningCount: prometheus.NewGauge(
			prometheus.GaugeOpts{
				Namespace: namespace,
				Name:      "workers_running_count",
				Help:      "The current number of running workers.",
			},
		),

 Thanks again for your helpful feedback!
