### ISSUE TITLE
JOSDK 3.2.0 shouldn't be used anymore, it's been superseded by 4.0.0

### ISSUE THREAD

**Issue by metacosm** [AbdelrhmanHamouda/locust-k8s-operator#38]
https://github.com/AbdelrhmanHamouda/locust-k8s-operator/blob/b940e0c28c9a0dcad78b81e232e97ec5df16e1d7/gradle/dependencies.gradle#L15

**Comment by AbdelrhmanHamouda** [comment]
hello @metacosm, 
I have merged your PR. However, I won't close this issue just yet. 

I must of missed something, but when the merge to master happened, you are not showing as contributor. I would like to address this before the issue is closed. 

If you already know what went wrong, please feel free to share with me and I'll correct it!
