### ISSUE TITLE
[Feature request] Enable setting the exporter image repository and tag from Helm's values file

### ISSUE THREAD

**Issue by jachinte** [AbdelrhmanHamouda/locust-k8s-operator#51]
**Is your feature request related to a problem? Please describe.**
It would be great if I could upgrade the locust-exporter image without having to compile the operator and create a new release.

**Describe the solution you'd like**
Move constants `EXPORTER_IMAGE_*` from `Constants.java` to `values.yaml`.

**Describe alternatives you've considered**
Perhaps the `SysConfig` class is the most appropriate place to declare these parameters? They'd have to be declared in several places, including Micronaut's `application.yml`, and Helm's `values.yaml` and `deployment.yaml`.

**Additional context**
I'm willing to implement this change, in case you think it'd be a good addition to the repository.

**Comment by AbdelrhmanHamouda** [comment]
Hello, 
Generally speaking, I get your point, that being said, locust_exporter is a very stable tool that doesn't get updated much since it seems to be feature complete (at least from the maintainer perspective). The last release before the current one was in June 2021. 

I foresee that the Operator will have much more frequent releases than any potential version updates of the locust_exporter tool. Thus, you can always rely on knowing that you would get the latest release from them very soon. Even sooner with reporting an issue if you need it urgently. 

Side notes:
- Why I am very carful and cautious about what gets included in HELM, CRD & CR? 
  - One of the main goals and important objectives of the Operator is to "abstract the cloud" and lower the barrier of entry. Meaning to make running performance on the cloud very very easy to any level of user. One of my reservations that i have against similar Operators for other tools is that their CRD and HELM is very complex and "scary" to the untrained eye. This makes it so the adoption is lower than  expected because so many people will stop as soon as they open any of those files. Of course this doesn't happen because of one change, but rather many changes over time. Thus I am extremely carful about this. 
- I can also foresee that you maybe interested in this feature to use a custom exporter, if this is indeed the case, I would invite you to share it and maybe we can include it in the Operator as a replacement for the current exporter.

**Comment by jachinte** [comment]
Hello @AbdelrhmanHamouda,

I see your point and definitely agree with you on being cautious. My main motivation to open this issue was to be able to inject my own exporter, which at the time was the new version of the locust exporter.
